pipeline{
agent any
tools {
  terraform 'Terraform-1'
}
  stages{
    stage("Terraform Init"){
      steps{
      sh 'terraform init'
      }
    }
    
    stage("Terraform Apply"){
      steps{
      sh 'terraform apply --auto-approve'
      }
    }
  }
}
